const ErrorCode = {
  DEVICE_NOT_FOUND: 'ID_DEVICE_NOT_FOUND',
  EVENT_NOT_SUPPORTED: 'ID_EVENT_NOT_SUPPORTED',
  DEVICE_DISCONNECTED: 'ID_DEVICE_DISCONNECTED',
  OPERATION_FAILED: 'ID_OPERATION_FAILED',
} as const;

export default ErrorCode;
